version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "4711:4711"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.12.2"
    volumes:
      - ../minecraft/data:/data
      - ../minecraft/plugins:/data/plugins
    restart: unless-stopped

  jupyter:
    build: ./
    container_name: jupyterlab
    volumes:
      - ../notebooks:/home/jovyan
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - minecraft
    restart: unless-stopped
